name: Build and Test
on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v1

      - name: fmt
        run: gofmt -s .

      - name: Lint
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20

      - name: Check out code
        uses: actions/checkout@v1

      - name: Run Unit tests.
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      
      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage1.xml,./coverage2.xml
          verbose: true
          
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 
      uses: actions/setup-go@v1
      with:
        go-version: 1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .
